const GAS_WEB_APP_URL="https://script.google.com/macros/s/AKfycbwD0Wmgte1oiTCl0UvgzC_-618qD72JPyKOB7PPyw7SFO6MAMR5YnHGRAxmOz6MVB11/exec";
const START_TIME="16:00",END_TIME="22:00";
const monthSelect=document.getElementById("targetMonth"),dateSelect=document.getElementById("targetDate"),loadBtn=document.getElementById("loadBtn"),clearBtn=document.getElementById("clearBtn"),saveBtn=document.getElementById("saveBtn"),statusBox=document.getElementById("statusBox"),assignmentArea=document.getElementById("assignmentArea"),draftArea=document.getElementById("draftArea");
let currentRows=[],currentLessons=[],assignments=new Map();
function jsonp(action,params={}){return new Promise((resolve,reject)=>{const cb="smsShiftCallback_"+Date.now()+"_"+Math.floor(Math.random()*10000);window[cb]=data=>{resolve(data);delete window[cb];script.remove();};const q=new URLSearchParams({action,callback:cb,...params});const script=document.createElement("script");script.src=GAS_WEB_APP_URL+"?"+q.toString();script.onerror=()=>reject(new Error("読み込み失敗"));document.body.appendChild(script);});}
function setupMonths(){monthSelect.innerHTML="";const now=new Date();for(let i=-1;i<=10;i++){const d=new Date(now.getFullYear(),now.getMonth()+i,1),text=`${d.getFullYear()}年${d.getMonth()+1}月`;const opt=document.createElement("option");opt.value=text;opt.textContent=text;if(i===1)opt.selected=true;monthSelect.appendChild(opt);}setupDates();}
function parseMonthText(text){const m=text.match(/(\d{4})年(\d{1,2})月/);return m?{year:Number(m[1]),month:Number(m[2])}:null;}
function setupDates(){dateSelect.innerHTML="";const p=parseMonthText(monthSelect.value);if(!p)return;const last=new Date(p.year,p.month,0).getDate();for(let d=1;d<=last;d++){const value=`${p.year}-${String(p.month).padStart(2,"0")}-${String(d).padStart(2,"0")}`;const opt=document.createElement("option");opt.value=value;opt.textContent=`${d}日`;dateSelect.appendChild(opt);}}
function timeToMinutes(t){const [h,m]=String(t).split(":").map(Number);return h*60+m;}function minutesToTime(min){return `${String(Math.floor(min/60)).padStart(2,"0")}:${String(min%60).padStart(2,"0")}`;}
function makeSlots(){const out=[];for(let t=timeToMinutes(START_TIME);t<timeToMinutes(END_TIME);t+=30)out.push({start:t,end:t+30,label:`${minutesToTime(t)}～${minutesToTime(t+30)}`});return out;}
function subtractIntervals(base,blocks){let intervals=[base];blocks.forEach(block=>{const next=[];intervals.forEach(intv=>{if(block.end<=intv.start||block.start>=intv.end)next.push(intv);else{if(block.start>intv.start)next.push({start:intv.start,end:block.start});if(block.end<intv.end)next.push({start:block.end,end:intv.end});}});intervals=next;});return intervals.filter(i=>i.end>i.start);}
function lessonBlocks(row){return(row.normalLessons||[]).map(name=>{const l=currentLessons.find(x=>String(x.name)===String(name));return l?{start:timeToMinutes(l.start),end:timeToMinutes(l.end)}:null;}).filter(Boolean);}
function standardBlocks(row){return(row.standard||[]).map(s=>s.start&&s.end?{start:timeToMinutes(s.start),end:timeToMinutes(s.end)}:null).filter(Boolean);}
function freeIntervals(row){return subtractIntervals({start:timeToMinutes(row.workStart),end:timeToMinutes(row.workEnd)},[...lessonBlocks(row),...standardBlocks(row)].sort((a,b)=>a.start-b.start));}
function contains(intervals,slot){return intervals.some(i=>i.start<=slot.start&&i.end>=slot.end);}
function availableTeachers(slot){return currentRows.filter(r=>contains(freeIntervals(r),slot)).map(r=>r.teacher);}
function renderAssignment(){assignmentArea.innerHTML="";makeSlots().forEach(slot=>{const row=document.createElement("div");row.className="slot-row";const names=availableTeachers(slot),current=assignments.get(slot.label)||[],checks=document.createElement("div");checks.className="checks";if(!names.length)checks.innerHTML='<span class="empty">該当なし</span>';else names.forEach(name=>{const label=document.createElement("label");label.className="teacher-check";label.innerHTML=`<input type="checkbox" value="${name}"> ${name}`;const input=label.querySelector("input");input.checked=current.includes(name);if(input.checked)label.classList.add("selected");input.addEventListener("change",()=>{label.classList.toggle("selected",input.checked);const selected=[...checks.querySelectorAll("input:checked")].map(i=>i.value);selected.length?assignments.set(slot.label,selected):assignments.delete(slot.label);renderDraft();});checks.appendChild(label);});row.innerHTML=`<div class="slot-time">${slot.label}</div>`;row.appendChild(checks);assignmentArea.appendChild(row);});}
function renderDraft(){draftArea.innerHTML="";if(assignments.size===0){draftArea.className="empty";draftArea.textContent="未割当です。";return;}draftArea.className="";[...assignments.entries()].forEach(([time,teachers])=>{const item=document.createElement("div");item.className="draft-item";item.innerHTML=`<div class="draft-time">${time}</div><div class="draft-teacher">${teachers.join("・")}</div>`;draftArea.appendChild(item);});}
async function loadData(){statusBox.className="status neutral";statusBox.textContent="読み込み中です…";assignments.clear();renderDraft();try{const latest=await jsonp("getLatest",{month:monthSelect.value});const finalShift=await jsonp("getFinalShift",{month:monthSelect.value,date:dateSelect.value});currentLessons=latest.lessons||[];currentRows=(latest.rows||[]).filter(r=>r.date===dateSelect.value);(finalShift.rows||[]).forEach(r=>{if(!assignments.has(r.time))assignments.set(r.time,[]);assignments.get(r.time).push(r.teacher);});renderAssignment();renderDraft();statusBox.className="status success";statusBox.textContent=`${monthSelect.value} / ${dateSelect.value} を読み込みました。`;}catch(e){console.error(e);statusBox.className="status error";statusBox.textContent="読み込みに失敗しました。";}}
function buildSavePayload(){const rows=[];[...assignments.entries()].forEach(([time,teachers])=>teachers.forEach(teacher=>rows.push({time,teacher})));return{version:"5.0-4",month:monthSelect.value,date:dateSelect.value,rows};}
async function saveShift(){const payload=buildSavePayload();if(!payload.rows.length){alert("保存するシフトがありません。");return;}if(!confirm(`${payload.date} の完成シフトを保存します。既存データは上書きされます。`))return;try{saveBtn.disabled=true;statusBox.className="status neutral";statusBox.textContent="保存中です…";await fetch(GAS_WEB_APP_URL,{method:"POST",mode:"no-cors",headers:{"Content-Type":"text/plain;charset=utf-8"},body:JSON.stringify({action:"saveShift",payload})});statusBox.className="status success";statusBox.textContent="完成シフトを保存しました。";alert("完成シフトを保存しました。");}catch(e){console.error(e);statusBox.className="status error";statusBox.textContent="保存に失敗しました。";alert("保存に失敗しました。");}finally{saveBtn.disabled=false;}}
clearBtn.addEventListener("click",()=>{assignments.clear();renderAssignment();renderDraft();});loadBtn.addEventListener("click",loadData);saveBtn.addEventListener("click",saveShift);monthSelect.addEventListener("change",()=>{setupDates();});setupMonths();renderDraft();
